// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdY_j7VAmp0oux9o8ZQFOV_gUZX5Eg4es',
    appId: '1:1078751560968:web:a5aff535b5fc93351798bd',
    messagingSenderId: '1078751560968',
    projectId: 'm3loma-f3550',
    authDomain: 'm3loma-f3550.firebaseapp.com',
    storageBucket: 'm3loma-f3550.firebasestorage.app',
    measurementId: 'G-WNHN33P1FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQAIYdt-hLHSK44qm0kTdaYa9hKQ15NME',
    appId: '1:1078751560968:android:9adf5dda29495daf1798bd',
    messagingSenderId: '1078751560968',
    projectId: 'm3loma-f3550',
    storageBucket: 'm3loma-f3550.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnSojcrQE0QI2jt3EfyTsHSARSUo0b1XY',
    appId: '1:1078751560968:ios:2ce9d94502cd8b151798bd',
    messagingSenderId: '1078751560968',
    projectId: 'm3loma-f3550',
    storageBucket: 'm3loma-f3550.firebasestorage.app',
    iosClientId: '1078751560968-b0vm4049r4u5hgt2kos829fltk4qg0gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.m3loma',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnSojcrQE0QI2jt3EfyTsHSARSUo0b1XY',
    appId: '1:1078751560968:ios:2ce9d94502cd8b151798bd',
    messagingSenderId: '1078751560968',
    projectId: 'm3loma-f3550',
    storageBucket: 'm3loma-f3550.firebasestorage.app',
    iosClientId: '1078751560968-b0vm4049r4u5hgt2kos829fltk4qg0gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.m3loma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdY_j7VAmp0oux9o8ZQFOV_gUZX5Eg4es',
    appId: '1:1078751560968:web:f6d418eb0bb81a2a1798bd',
    messagingSenderId: '1078751560968',
    projectId: 'm3loma-f3550',
    authDomain: 'm3loma-f3550.firebaseapp.com',
    storageBucket: 'm3loma-f3550.firebasestorage.app',
    measurementId: 'G-C0J3G0J5HM',
  );
}
